# Generated by Django 5.0.6 on 2024-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_alter_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('finished', 'Finished')], default='lobby', max_length=10),
        ),
    ]
