# Generated by Django 3.2.25 on 2024-06-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0005_auto_20240625_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creator',
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to='dinner.player'),
        ),
    ]
