# Generated by Django 3.2.25 on 2024-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0006_auto_20240625_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guessing',
            field=models.BooleanField(default=False),
        ),
    ]
