# Generated by Django 3.2.25 on 2024-06-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0007_player_guessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bot',
            field=models.BooleanField(default=False),
        ),
    ]
