# Generated by Django 3.2.25 on 2024-06-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0009_player_has_viewed_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
