# Generated by Django 3.2.25 on 2024-06-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0010_answer_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='display_order',
            field=models.IntegerField(),
        ),
    ]
