# Generated by Django 3.2.25 on 2024-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0011_alter_answer_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
